CREATE TABLE [dbo].[RentDetails]
(
	OrderId UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    CustomerId UNIQUEIDENTIFIER NOT NULL,
	Name NVARCHAR(100),
    MovieId UNIQUEIDENTIFIER NOT NULL,
	Title NVARCHAR(100),
    OrderDate DATETIME NULL,
	TotalPrice DECIMAL(5,2)
);